//
// Created by Anton on 2021-05-25.
//

#ifndef USIDE_SRC_PARSER_INCLUDE_PARSER_INCLUDE_H
#define USIDE_SRC_PARSER_INCLUDE_PARSER_INCLUDE_H

#include "../h/parser.h"

#endif //USIDE_SRC_PARSER_INCLUDE_PARSER_INCLUDE_H
