//
// Created by Anton on 2021-05-22.
//

#ifndef USIDE_SRC_FRAMEBUFFER_INCLUDE_FRAMEBUFFER_INCLUDE_H
#define USIDE_SRC_FRAMEBUFFER_INCLUDE_FRAMEBUFFER_INCLUDE_H

#include "../h/framebuffer.h"

#endif //USIDE_SRC_FRAMEBUFFER_INCLUDE_FRAMEBUFFER_INCLUDE_H
