#message(${src_dir})

file(GLOB_RECURSE file_list RELATIVE ${src_dir} ${src_dir}/*)

foreach( each_file ${file_list} )
    set(destination_file "${dst_dir}/${each_file}")
    set(source_file "${src_dir}/${each_file}")
    file(TIMESTAMP ${source_file} source_timestamp)
    file(TIMESTAMP ${destination_file} destination_timestamp)
    if(NOT EXISTS ${destination_file} OR NOT ${source_timestamp} STREQUAL ${destination_timestamp} AND ${source_file} IS_NEWER_THAN ${destination_file})
        get_filename_component(destination_dir ${destination_file} DIRECTORY)
        file(COPY ${source_file} DESTINATION ${destination_dir})
        message("Updating:")
        message("    ${source_timestamp} ${source_file}")
        message("    ${destination_timestamp} ${destination_file}")
    endif()
endforeach()